server:
  port: 9527


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心动态注册路由 负载均衡
      routes:
        - id: payment_routh #payment_route #路由的ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/** #断言，路径相匹配的进行路由
            - After=2020-05-14T10:58:06.546+08:00[Asia/Shanghai]

        - id: payment_routh2 #payment_route #路由的ID,没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
            - Between=2020-05-14T10:58:06.546+08:00[Asia/Shanghai],2020-12-14T10:58:06.546+08:00[Asia/Shanghai]


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false
