server:
  port: 80


eureka:
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      # 相互注册
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com.7002/eureka #集群版
      defaultZone: http://eureka7001.com:7001/eureka #单机版



#设置feign客户端超时时间，适用于网路状况正常的情况下
#延时操作
#ribbon:
#指的是简历连接所用的时间，适用于网络状况正常的情况下，连段连接所用的时间
#  ReadTimeout: 3000
#指的是建立连接后从服务器读取到可用资源所用时间
#  ConnectTimeout: 3000

feign:
  hystrix:
    enabled: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root

#日志增强
logging:
  level:
    #feign日志以什么级别监控哪个接口
    org.shun.cloud.service.PaymentFeignService: debug
